lane :test do
  codemagic(
    workflow_id: "YOUR_WORKFLOW_ID",
    app_id: "YOUR_APP_ID",
    branch: "YOUR_BRANCH",
    tag: "YOUR_TAG",
    auth_token: "YOUR_AUTH_TOKEN",
    download: {
      artefacts: ["ipa"],
      build_path: "./build/"
    },
    environment: {
      variables: {
        ENV: "production"
      },
      softwareVersions: {
        flutter: "stable",
        xcode: "latest",
        cocoapods: "default"
      }
    }
  )
end
